#
# Build the cv
#
name: Build
on:
  pull_request:
  push:
    branches:
      - master
    # Schedule daily builds
    schedule:
      - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install TinyTeX
        run: |
          curl -sL "https://yihui.org/tinytex/install-bin-unix.sh" | sh
          echo "${HOME}/bin" >> $GITHUB_PATH

      - name: Install LaTeX packages
        run: |
          tlmgr install \
            anyfontsize \
            ctex \
            datetime \
            enumitem \
            etaremune \
            everysel \
            fancyhdr \
            fmtcount \
            geometry \
            hyperref \
            sourcesanspro \
            sourcecodepro \
            xcolor

      - name: Build CV
        run: make
